- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: '$(Release)'
    sdk: '$(ipados)'
    packageApp: true
    exportPath: 'output/$(ipados)/$(Release)'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPad Air 2,OS=14.4.1'